-- MySQL Script generated by MySQL Workbench
-- dom 16 dic 2018 23:03:39 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema smartTrainingDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `smartTrainingDB` ;

-- -----------------------------------------------------
-- Schema smartTrainingDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smartTrainingDB` DEFAULT CHARACTER SET utf8 ;
USE `smartTrainingDB` ;

-- -----------------------------------------------------
-- Table `smartTrainingDB`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartTrainingDB`.`country` ;

CREATE TABLE IF NOT EXISTS `smartTrainingDB`.`country` (
  `idcountry` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `createdCountry` DATETIME NOT NULL,
  `modifiedCountry` DATETIME NOT NULL,
  PRIMARY KEY (`idcountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartTrainingDB`.`institution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartTrainingDB`.`institution` ;

CREATE TABLE IF NOT EXISTS `smartTrainingDB`.`institution` (
  `idinstitution` INT NOT NULL,
  `nameInstitution` VARCHAR(45) NOT NULL,
  `createdInstitution` DATETIME NOT NULL,
  `modifiedInstitution` DATETIME NOT NULL,
  `country` INT NOT NULL,
  PRIMARY KEY (`idinstitution`),
  INDEX `fk_institution_country_idx` (`country` ASC),
  CONSTRAINT `fk_institution_country`
    FOREIGN KEY (`country`)
    REFERENCES `smartTrainingDB`.`country` (`idcountry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
