-- MySQL Script generated by MySQL Workbench
-- sáb 20 oct 2018 21:39:01 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vhlHunter
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vhlHunter` ;

-- -----------------------------------------------------
-- Schema vhlHunter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vhlHunter` DEFAULT CHARACTER SET utf8 ;
USE `vhlHunter` ;

-- -----------------------------------------------------
-- Table `vhlHunter`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vhlHunter`.`country` ;

CREATE TABLE IF NOT EXISTS `vhlHunter`.`country` (
  `idcountry` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(450) NOT NULL,
  `createdCountry` DATETIME NOT NULL,
  `modifiedCountry` DATETIME NOT NULL,
  PRIMARY KEY (`idcountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vhlHunter`.`institution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vhlHunter`.`institution` ;

CREATE TABLE IF NOT EXISTS `vhlHunter`.`institution` (
  `idinstitution` INT NOT NULL AUTO_INCREMENT,
  `nameInstitution` VARCHAR(450) NOT NULL,
  `createdInstitution` DATETIME NOT NULL,
  `modifiedInstitution` DATETIME NOT NULL,
  `country` INT NOT NULL,
  PRIMARY KEY (`idinstitution`),
  INDEX `fk_institution_country_idx` (`country` ASC),
  CONSTRAINT `fk_institution_country`
    FOREIGN KEY (`country`)
    REFERENCES `vhlHunter`.`country` (`idcountry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vhlHunter`.`userService`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vhlHunter`.`userService` ;

CREATE TABLE IF NOT EXISTS `vhlHunter`.`userService` (
  `iduserService` INT NOT NULL AUTO_INCREMENT,
  `userServicecol` VARCHAR(450) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nameUser` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `createdUser` DATETIME NOT NULL,
  `modifiedUser` DATETIME NOT NULL,
  `institution` INT NOT NULL,
  PRIMARY KEY (`iduserService`),
  INDEX `fk_userService_institution1_idx` (`institution` ASC),
  CONSTRAINT `fk_userService_institution1`
    FOREIGN KEY (`institution`)
    REFERENCES `vhlHunter`.`institution` (`idinstitution`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vhlHunter`.`job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vhlHunter`.`job` ;

CREATE TABLE IF NOT EXISTS `vhlHunter`.`job` (
  `idjob` INT NOT NULL,
  `nameJob` VARCHAR(450) NOT NULL,
  `description` VARCHAR(4500) NOT NULL,
  `statusJob` VARCHAR(45) NOT NULL,
  `dateJob` DATETIME NOT NULL,
  `nameFileInput` VARCHAR(45) NOT NULL,
  `userService_iduserService` INT NOT NULL,
  PRIMARY KEY (`idjob`),
  INDEX `fk_job_userService1_idx` (`userService_iduserService` ASC),
  CONSTRAINT `fk_job_userService1`
    FOREIGN KEY (`userService_iduserService`)
    REFERENCES `vhlHunter`.`userService` (`iduserService`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vhlHunter`.`requestProcess`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vhlHunter`.`requestProcess` ;

CREATE TABLE IF NOT EXISTS `vhlHunter`.`requestProcess` (
  `idrequestProcess` INT NOT NULL,
  `nameRequest` VARCHAR(45) NOT NULL,
  `dateRequest` DATETIME NOT NULL,
  `statusRequest` VARCHAR(45) NOT NULL,
  `userService` INT NOT NULL,
  `job` INT NOT NULL,
  PRIMARY KEY (`idrequestProcess`),
  INDEX `fk_requestProcess_userService1_idx` (`userService` ASC),
  INDEX `fk_requestProcess_job1_idx` (`job` ASC),
  CONSTRAINT `fk_requestProcess_userService1`
    FOREIGN KEY (`userService`)
    REFERENCES `vhlHunter`.`userService` (`iduserService`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_requestProcess_job1`
    FOREIGN KEY (`job`)
    REFERENCES `vhlHunter`.`job` (`idjob`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
